import { Router } from "express";
import { db, calendarEventsTable, taxesTable, alertsTable } from "@workspace/db";
import { eq, and, sql } from "drizzle-orm";
import { authMiddleware, type AuthRequest } from "../middlewares/auth";
import { logger } from "../lib/logger";

const router = Router();

router.get("/calendar", authMiddleware, async (req: AuthRequest, res) => {
  try {
    const { month, year } = req.query;

    let conditions = [eq(calendarEventsTable.userId, req.userId!)];
    if (year && month) {
      const ym = `${year}-${String(month).padStart(2, "0")}`;
      conditions.push(sql`${calendarEventsTable.date} LIKE ${ym + "%"}`);
    } else if (year) {
      conditions.push(sql`${calendarEventsTable.date} LIKE ${year + "%"}`);
    }

    const events = await db.select().from(calendarEventsTable)
      .where(and(...conditions))
      .orderBy(calendarEventsTable.date);

    // Augment with DAS deadlines if month/year provided
    const enriched: any[] = [...events];
    if (year && month) {
      const pendingTaxes = await db.select().from(taxesTable)
        .where(and(
          eq(taxesTable.userId, req.userId!),
          eq(taxesTable.status, "pending"),
          sql`${taxesTable.dueDate} LIKE ${String(year) + "-" + String(month).padStart(2, "0") + "%"}`
        ));
      for (const tax of pendingTaxes) {
        enriched.push({
          id: `tax-${tax.id}`,
          title: `DAS ${tax.competence}`,
          description: `Vencimento DAS — R$ ${tax.amount.toFixed(2)}`,
          date: tax.dueDate,
          type: "das",
          isAutoGenerated: true,
          isDone: false,
        });
      }
    }

    enriched.sort((a, b) => a.date.localeCompare(b.date));
    res.json(enriched);
  } catch (err) {
    logger.error({ err }, "List calendar events error");
    res.status(500).json({ error: "Erro ao listar eventos" });
  }
});

router.post("/calendar", authMiddleware, async (req: AuthRequest, res) => {
  const { title, description, date, type } = req.body;
  if (!title || !date) {
    res.status(400).json({ error: "Campos obrigatórios: title, date" });
    return;
  }
  try {
    const [event] = await db.insert(calendarEventsTable).values({
      userId: req.userId!,
      title,
      description: description || null,
      date,
      type: type || "custom",
    }).returning();
    res.status(201).json(event);
  } catch (err) {
    logger.error({ err }, "Create calendar event error");
    res.status(500).json({ error: "Erro ao criar evento" });
  }
});

router.put("/calendar/:id", authMiddleware, async (req: AuthRequest, res) => {
  const { title, description, date, type, isDone } = req.body;
  try {
    const id = parseInt(req.params.id as string);
    const updateData: Record<string, unknown> = { updatedAt: new Date() };
    if (title !== undefined) updateData.title = title;
    if (description !== undefined) updateData.description = description;
    if (date !== undefined) updateData.date = date;
    if (type !== undefined) updateData.type = type;
    if (isDone !== undefined) updateData.isDone = isDone;

    const [event] = await db.update(calendarEventsTable).set(updateData)
      .where(and(eq(calendarEventsTable.id, id), eq(calendarEventsTable.userId, req.userId!)))
      .returning();
    if (!event) { res.status(404).json({ error: "Evento não encontrado" }); return; }
    res.json(event);
  } catch (err) {
    logger.error({ err }, "Update calendar event error");
    res.status(500).json({ error: "Erro ao atualizar evento" });
  }
});

router.delete("/calendar/:id", authMiddleware, async (req: AuthRequest, res) => {
  try {
    const id = parseInt(req.params.id as string);
    const [deleted] = await db.delete(calendarEventsTable)
      .where(and(eq(calendarEventsTable.id, id), eq(calendarEventsTable.userId, req.userId!)))
      .returning();
    if (!deleted) { res.status(404).json({ error: "Evento não encontrado" }); return; }
    res.json({ message: "Evento excluído" });
  } catch (err) {
    logger.error({ err }, "Delete calendar event error");
    res.status(500).json({ error: "Erro ao excluir evento" });
  }
});

export default router;
