import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { customFetch } from "./custom-fetch";

// ─── MEI Score ────────────────────────────────────────────────────────────────
export interface MeiScoreResult {
  score: number;
  label: string;
  details: {
    limitScore: number;
    taxScore: number;
    docScore: number;
    activityScore: number;
    profileScore: number;
  };
}

export interface MeiScoreHistory {
  id: number;
  userId: number;
  score: number;
  label: string;
  details: string | null;
  calculatedAt: string;
}

export function useGetMeiScore(options?: { enabled?: boolean }) {
  return useQuery<MeiScoreResult>({
    queryKey: ["meiScore"],
    queryFn: () => customFetch<MeiScoreResult>("/api/score"),
    staleTime: 5 * 60 * 1000,
    ...options,
  });
}

export function useGetMeiScoreHistory() {
  return useQuery<MeiScoreHistory[]>({
    queryKey: ["meiScoreHistory"],
    queryFn: () => customFetch<MeiScoreHistory[]>("/api/score/history"),
    staleTime: 10 * 60 * 1000,
  });
}

// ─── Calendar ─────────────────────────────────────────────────────────────────
export interface CalendarEvent {
  id: number | string;
  userId?: number;
  title: string;
  description?: string | null;
  date: string;
  type: string;
  isAutoGenerated?: boolean;
  isDone: boolean;
  createdAt?: string;
}

export interface CreateCalendarEventInput {
  title: string;
  description?: string;
  date: string;
  type?: string;
}

export interface UpdateCalendarEventInput {
  title?: string;
  description?: string;
  date?: string;
  type?: string;
  isDone?: boolean;
}

export function useGetCalendarEvents(params?: { month?: number; year?: number }) {
  const search = new URLSearchParams();
  if (params?.month) search.set("month", String(params.month));
  if (params?.year) search.set("year", String(params.year));
  const qs = search.toString() ? `?${search}` : "";

  return useQuery<CalendarEvent[]>({
    queryKey: ["calendarEvents", params],
    queryFn: () => customFetch<CalendarEvent[]>(`/api/calendar${qs}`),
    staleTime: 2 * 60 * 1000,
  });
}

export function useCreateCalendarEvent() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: CreateCalendarEventInput) =>
      customFetch<CalendarEvent>("/api/calendar", {
        method: "POST",
        body: JSON.stringify(data),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["calendarEvents"] }),
  });
}

export function useUpdateCalendarEvent() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: UpdateCalendarEventInput }) =>
      customFetch<CalendarEvent>(`/api/calendar/${id}`, {
        method: "PUT",
        body: JSON.stringify(data),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["calendarEvents"] }),
  });
}

export function useDeleteCalendarEvent() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: number) =>
      customFetch(`/api/calendar/${id}`, { method: "DELETE" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["calendarEvents"] }),
  });
}

// ─── Receipts ─────────────────────────────────────────────────────────────────
export interface Receipt {
  id: number;
  userId: number;
  clientName: string;
  clientCpfCnpj: string | null;
  description: string;
  amount: number;
  date: string;
  number: number;
  notes: string | null;
  createdAt: string;
}

export interface CreateReceiptInput {
  clientName: string;
  clientCpfCnpj?: string;
  description: string;
  amount: number;
  date: string;
  notes?: string;
}

export function useGetReceipts() {
  return useQuery<Receipt[]>({
    queryKey: ["receipts"],
    queryFn: () => customFetch<Receipt[]>("/api/receipts"),
    staleTime: 2 * 60 * 1000,
  });
}

export function useCreateReceipt() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: CreateReceiptInput) =>
      customFetch<Receipt>("/api/receipts", {
        method: "POST",
        body: JSON.stringify(data),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["receipts"] }),
  });
}

export function useDeleteReceipt() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: number) =>
      customFetch(`/api/receipts/${id}`, { method: "DELETE" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["receipts"] }),
  });
}

// ─── Admin ────────────────────────────────────────────────────────────────────
export interface AdminStats {
  totalUsers: number;
  newUsers: number;
  totalRevenue: number;
  unreadAlerts: number;
  recentActivity: any[];
  recentUsers: any[];
}

export function useGetAdminStats() {
  return useQuery<AdminStats>({
    queryKey: ["adminStats"],
    queryFn: () => customFetch<AdminStats>("/api/admin/stats"),
    staleTime: 60 * 1000,
  });
}

// ─── Activity Log ─────────────────────────────────────────────────────────────
export interface ActivityLogEntry {
  id: number;
  userId: number | null;
  action: string;
  entity: string | null;
  entityId: string | null;
  details: string | null;
  ipAddress: string | null;
  createdAt: string;
}

export function useGetActivityLog(limit?: number) {
  return useQuery<ActivityLogEntry[]>({
    queryKey: ["activityLog", limit],
    queryFn: () => customFetch<ActivityLogEntry[]>(`/api/activity${limit ? `?limit=${limit}` : ""}`),
    staleTime: 60 * 1000,
  });
}

// ─── Alerts: mark all read ────────────────────────────────────────────────────
export function useMarkAllAlertsRead() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: () =>
      customFetch("/api/alerts/read-all", { method: "PATCH" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["alerts"] }),
  });
}
